### ISSUE TITLE
Encryption improvements

### ISSUE THREAD

**Issue by lowleveldesign** [spetz/Lockbox#1]
The idea is very nice, but I have few concerns regarding the box user password management . You should really consider using one of the already implemented solutions (eg. ASP.NET Identity + MongoDB). If it is not feasible, please have a look at the https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNetCore.Identity/PasswordHasher.cs for inspiration. The problems which currently exists are:

- SHA512 used to generate user password's hash - hash functions are not supposed to be used in this context, PKBDF2 (Rfc2898DeriveBytes) is a much better choice (it is used in the ASP.NET Identity library, and you also use it few lines above the GetHash function :))
- when validating a hash you shouldn't be using SequenceEqual - its execution time varies depending on how many bytes are equal in the source and destination array, which may help the attacker in guessing the right password

Also consider replacing: `var algorithm = TripleDES.Create();` with `var algorithm = AES.Create();`

**Comment by spetz** [comment]
Hey,
Thank you for the remarks, as I'm definitely not a security expert :). I'm not a fan of ASP.NET Identity, therefore I'll take a look at the suggested _PasswordHasher_ solution.
I'll also fix the _SequenceEqual_ and for sure switch to AES256, as many people have already suggested.
